name: fEATs frontend

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

      - name: Run tests
        run: npm run test

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker container with 'latest' tag
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/feats-frontend:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Push Docker image (latest) to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/feats-frontend:latest

      - name: Push Docker image (version) to Docker Hub
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/feats-frontend:latest ${{ secrets.DOCKER_HUB_USERNAME }}/feats-frontend:${{ steps.package-version.outputs.current-version}}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/feats-frontend:${{ steps.package-version.outputs.current-version}}
