name: fEATs frontend

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Lint
        run: |
          npm run lint

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/

      - name: Run tests
        run: npm run test

      # Docker steps to run only when merged to main
      - name: Set up Docker
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v2

      - name: Build Docker container with 'latest' tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/feats-frontend:latest .

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: get-npm-version
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Push Docker image (latest) to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/feats-frontend:latest

      - name: Push Docker image (version) to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/feats-frontend:latest ${{ secrets.DOCKER_HUB_USERNAME }}/feats-frontend:${{ steps.package-version.outputs.current-version}}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/feats-frontend:${{ steps.package-version.outputs.current-version}}
